### ISSUE TITLE
Limit consumed tables?

### ISSUE THREAD

**Issue by ottomata** [mardambey/mypipe#11]
In a database with many writes and many tables, it would be useful to be able to specify a list of tables for which binlogs should be consumed.  Is this possible?

**Comment by andrioni** [comment]
I think MySQL itself doesn't keep separate binlogs, but you can write your own producer to filter the tables you want.

**Comment by mardambey** [comment]
@ottomata @andrioni we could potentially implement a white or black list that can be specified in the configuration such that only events with said db / table patterns will be published (or not published) downstream from mypipe.

**Comment by mardambey** [comment]
@ottomata 53dceb568a4867a408331e9344602a3b0073d5c4 addresses this. It gives the ability to plug into the event processing pipeline to allow (or not) the processing of an event. I've given a basic example; however one can do more advanced filtering.

Note that if this functionality is used you also have to look into `mypipe.error.quit-on-empty-mutation-commit-failure` and set it to `false` otherwise the system will fail on empty transactions.
