### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by akumarb2010** [mardambey/mypipe#2]
Hi,

I am trying understand this project for replicating mysql db data to hadoop. I configured application.conf.

After configuring application.conf, what is the procedure? And I couldn't understand the mechanism for processing MySQL binlogs, can you please explain this?

**Comment by mardambey** [comment]
Hi @akumarb2010,

Can you take a look at commits 39c11a413bf644bb529cbe7650edd3f90e624662 and 4186bb913bfab58f08eee2f1eb07cfedeafaf3c9? I've added some documentation on how events are encoded and pushed into Kafka (generically for now). Let me know if this is unclear or if you have any questions and I'll try to address them.

I'll also add another section on how binary logs are processed and handled soon! (=

Thanks!

**Comment by mardambey** [comment]
See also c671593dc7719dd8a8f4fee9b2d0adc72b350c09 - where I start describing how mypipe works on the inside.

**Comment by akumarb2010** [comment]
Thanks a lot for your explanation.

I have one more query. Can you please clarify below query?
If the source table(MySQL table) doesn't have any primary key, then how updates are taken care?

**Comment by mardambey** [comment]
Primary keys are optional to the core functionality; if a table does not have one then the internal `mypipe.api.Table` instance will have a `None` for the `primaryKey` value.

In this case, things will proceed _almost_ as usual.
- The `StdoutProcuder` will output the query to standard out with a missing `where` clause
- The Kafka producers will pump the associated Avro records into the correct topics with both the old and new values, not caring about primary keys.

In other words, at this point in time, we don't really rely on the primary key for anything.

Take a look at commit 9d6e8c92008b761240f76b566aafaf8e71133bcb if you're interested in reading out data written into Kafka generically and presenting it in a human readable format on standard out. Here's a sample update to a table without primary key:

`create table foo (user varchar(16), pass varchar(16));`

`insert into foo values ('one', 'two');`

`update foo set user="ONE" where user="one";`

Generates:

```
{
    "database": "mypipe",
    "table": "foo",
    "tableId": 2094,
    "old_integers": {},
    "old_strings": {
        "user": "one",
        "pass": "two"
    },
    "old_longs": {},
    "new_integers": {},
    "new_strings": {
        "user": "ONE",
        "pass": "two"
    },
    "new_longs": {}
}
```

Also, thanks to this question I fixed a bug in the Kafka producers as shown here 576a2eba0208371718faf6b230636b4b2c895a70.

**Comment by bahchis** [comment]
Hi @mardambey,
Your project seems exactly what I am looking for, but I am missing some simple getting started tutorial.
Is your project intended to be used as a library or an utility? Could you please share some simple example of making row changes in mysql table sent to Kafka?

Thanks

**Comment by mardambey** [comment]
@bahchis, I've started working on documentation in order to get started with mypipe. You can take a look at commit 55b6cd51e59a59938106f287aca726abb0bb5160 or simply look at the README.md file in the root of the project directory.

I'll be adding to this documentation over the coming days and I'll describe how to push mutations into Kafka and consume them back out in your own code.

Regarding your question whether mypipe is intended to be a library or a utility; it is actually both. The `mypipe-api` project does just that - it offers a way to build programs that latch onto MySQL binary logs. The `mypipe-runner` uses all the mypipe sub-projects in order to build the utility that allows the shuttling of binary log events to downstream systems.

Don't hesitate to ask if you have additional questions.

**Comment by mardambey** [comment]
@bahchis, additional documentation (5615409df0bcf96b6ed1157a1f4dcd9d778a45c9) on producing events into Kafka generically, and how to quickly consume them on the console.
