### ISSUE TITLE
writing the initial snapshot to Kafka by turning every single row in the database into a message

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#28]
One feature available in bottled-water is  writing the initial snapshot to Kafka by turning every single row in the database into a message,  When the snapshot is done, every row that is inserted, updated or deleted similarly turns into a message in the same topic.can we achieve the same with mypipe ??

**Comment by mardambey** [comment]
This is a great feature. I'd like to add something along these lines.

Currently, I'm really afk (writing this from my phone) as I am in the
hospital for a bit. I'll give you updates as soon as I can unless yourself
or others want to start working on this first (=

Cheers!

On Monday, 12 October 2015, bbnsumanth notifications@github.com wrote:

> One feature available in bottled-water is writing the initial snapshot to
> Kafka by turning every single row in the database into a message, When the
> snapshot is done, every row that is inserted, updated or deleted similarly
> turns into a message in the same topic.can we achieve the same with mypipe
> ??
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mardambey/mypipe/issues/28.

## 

Hisham Mardam-Bey
http://hisham.cc/

**Comment by bbnsumanth** [comment]
Thanks  mardambey.

**Comment by mardambey** [comment]
I've started working on this. Take a look at 144194eb102c4b9f1ac488af3ced887969a97ccf and previous commits. The implementation is still incomplete and hard coded, I'll improve it over the next few days / weeks.

The main idea so far is that we take a consistent snapshot from MySQL and capture the binary log position before we do so. We then get back a bunch of rows via a `select *`, turn those rows into `SelectEvent`s, then feed them into a `SelectConsumer` that can just be connected via a `Pipe` to any downstream producer (currently `StdoutProducer`). 

Eventually this should be able to fetch rows from the desired tables without buffering the entire table into memory, it should save the binlog position when done, and it should be able to use the `Kafka*` producers in order to push into Kafka via Avro encoding.

**Comment by FelixGV** [comment]
Nice @mardambey !

Quick question: do you really need the dump to be a consistent snapshot? It seems to me you could do it completely outside the scope of a MySQL transaction, like this:
1. Record the DB's current bin log position.
2. Do a full scan of the table(s), producing each row into your Kafka topic.
3. Replay the bin log from the position recorded in step 1.
4. Optionally, record the Kafka offsets when you reach the tip of the bin log (or when you are within a certain lag threshold, say <5 seconds from the current time or whatever).
5. Let Kafka log compaction take care of eliminating duplicates keys.

Once compaction runs once, the topic's content would be fully ordered. Before log compaction runs (or if you don't want to run it at all), then you need to make sure you consume at least up to the Kafka offset recorded in step 4, because the events prior to that are potentially out of order.

-F

**Comment by wushujames** [comment]
@FelixGV, that would basically be "eventually consistent" before the offset in step 4, and consistent afterwards, right?

**Comment by FelixGV** [comment]
I guess you could say it that way, yes.

Basically, between the time when you to read (and push to Kafka) the first row in your table up to the time when you push the last row, there could be more writes that come in and which are persistent on the bin log. So when you re-apply that delta of bin logs at the tip of your Kafka topic, there could be a situation where the content of your Kafka topic appears to "go back in time":
- UPDATE row xyz to value 'foo' at time 11. // came from the initial snapshot
- UPDATE row xyz to value 'bar' at time 10. // came from the bin log
- UPDATE row xyz to value 'foo' at time 11. // came from the bin log

Once you're caught up on the bin log, then the state of the consuming database should be fully consistent, and everything which is consumed after that Kafka offset would continue being strictly ordered (assuming Kafka is configured with strong fidelity settings, like `max.inflight.requests=1`, `min.isr>1`, `unclean.leader.election.enable=false`, etc.).

-F

**Comment by mardambey** [comment]
Initial work done for now, we'll open other issues accordingly.

**Comment by wushujames** [comment]
This is really cool. Nice work!

**Comment by mardambey** [comment]
@wushujames, cheers mate (=
