### ISSUE TITLE
Request for better documentation on using specific schema.

### ISSUE THREAD

**Issue by bbnsumanth** [mardambey/mypipe#29]
Couldn't figure out how to register the schema in a schema repo and how mypipe is capturing them.
Can we use confluent platform's schemaRegistry for  registry specific schema of mypipe?

**Comment by FelixGV** [comment]
The schema repo embedded in the mypipe code base is based on the implementation in [AVRO-1124](https://issues.apache.org/jira/browse/AVRO-1124). Another fork, also based on AVRO-1124 but with slightly more fixes and improvements, can be found here: https://github.com/schema-repo/schema-repo

The AVRO-1124 / schema-repo project has slightly less restrictive semantics that Confluent's schema registry (i.e.: the schema ID can be pretty much anything, instead of being restricted to 4 bytes globally unique integers only). In that sense, the schema-repo APIs can support a super-set of the Confluent APIs... If there is a desire to support interop with many schema-repo/registries, then it should be trivial to use the schema-repo APIs as the common abstraction, and leverage the Confluent code in order to interact with a Confluent schema-registry from the schema-repo APIs. This way, a project such as mypipe can code against a single API, and interact with any schema management solution.

-F

**Comment by bbnsumanth** [comment]
Thank you,FelixGV.

**Comment by mardambey** [comment]
We now use https://github.com/schema-repo/schema-repo (=

**Comment by FelixGV** [comment]
That's cool! Well done @mardambey (: !

**Comment by bbnsumanth** [comment]
Thanks for the reply :)
